import Head from 'next/head'
import { useCallback } from 'react'
import { Footer } from '../components/Footer'
import { Header } from '../components/Header'
import { Main } from '../components/Main'
import styles from '../styles/Home.module.css'



export default function Home() {
  
  const foo = 1;
  const handleClick = useCallback((e) => {
    console.log(e.target.href);
    e.preventDefault();
    alert(foo);
  }, []);
  return (


    <div className={styles.container}>
      <Head>
        <title>index page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <a href="/about"onClick={handleClick}>
       ボタン
      </a>
     
      <Main page="index"/>
      <Footer />
    </div>
  )
}
